### ISSUE TITLE
NBT更新了

### ISSUE THREAD

**Issue by 1602279568** [wifi-left/ChineseNBTExplorer#1]
NBT更新到2.8.0了呀！作者速速更新！

**Comment by wifi-left** [comment]
嗯？没有更新啊
NBT和原来的应该通用吧

**Comment by mcxiaochenn** [comment]
https://github.com/jaquadro/NBTExplorer/releases/tag/v2.8.0-win
更新到2.8了

**Comment by wifi-left** [comment]
行

**Comment by wifi-left** [comment]
本项目最初就修改于最新的2.8.0，所以无需更新。
